services:
  mysql:
    image: mysql:8.0
    container_name: sentinel-mysql
    command: --skip-host-cache --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sentinel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: sentinel-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: sentinel-redis
    ports:
      - "6380:6379"

  backend:
    build: .
    container_name: sentinel-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
      - mongodb
      - redis

volumes:
  mysql_data:
  mongo_data:
