apiVersion: v1
kind: Secret
metadata:
  name: sentinel-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "REPLACE_ME"
  DATABASE_URL: "mysql://root:REPLACE_ME@sentinel-mysql:3306/sentinel"
  SESSION_SECRET: "REPLACE_ME"
  GOOGLE_CLIENT_ID: "REPLACE_ME"
  GOOGLE_CLIENT_SECRET: "REPLACE_ME"
  SQS_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/799025182472/sentinel-request-logging"
